var departmentsData = [["Code", "Name"],
["AE","Aerospace Engineering"],
["AG","Agricultural and Food Engineering"],
["AR","Architecture and Regional Planning"],
["BT","Biotechnology"],
["CE","Civil Engineering"],
["CH","Chemical Engineering"],
["CS","Computer Science and Engineering"],
["EC","Electronics and Electrical Communication Engg."],
["EE","Electrical Engineering"],
["GG","Geology and Geophysics"],
["HS","Humanities and Social Sciences"],
["IS","Industrial and Systems Engineering"],
["MA","Mathematics"],
["ME","Mechanical Engineering"],
["MI","Mining Engineering"],
["MT","Metallurgical and Materials Engineering"],
["OE","Ocean Engg and Naval Architecture"],
["PH","Physics"]
];